import logging
from fastapi import APIRouter, Depends, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session

from app.db.database import get_db
from app.schemas.user import UserCreate, UserOut
from app.schemas.token import Token
from app.services import auth_service
from app.api.deps import get_current_user
from app.models.user import User
from app.services.activity_service import activity_service

logger = logging.getLogger("todo_api")

router = APIRouter(prefix="/api/v1/auth", tags=["auth"])


@router.post("/register", response_model=UserOut, status_code=status.HTTP_201_CREATED)
def register(user_in: UserCreate, db: Session = Depends(get_db)):
    """Create a new user account."""
    user = auth_service.register_user(db, user_in)
    activity_service.log_action(db, user.id, "login", f"Registered user {user.email}")
    logger.info("New user registered: %s", user.email)
    return user


@router.post("/login", response_model=Token)
def login(user_in: UserCreate, db: Session = Depends(get_db)):
    """
    Authenticate and return a JWT access token using JSON credentials.
    """
    user = auth_service.authenticate_user(db, user_in.email, user_in.password)
    token = auth_service.create_token_for_user(user)
    activity_service.log_action(db, user.id, "login", f"Logged in {user.email}")
    logger.info("User logged in: %s", user.email)
    return Token(access_token=token)


@router.post("/login/form", response_model=Token)
def login_form(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db),
):
    """
    Authenticate and return a JWT access token using OAuth2 password form data.
    This endpoint is used by the autogenerated Swagger UI.
    """
    user = auth_service.authenticate_user(db, form_data.username, form_data.password)
    token = auth_service.create_token_for_user(user)
    activity_service.log_action(db, user.id, "login", f"Logged in {user.email}")
    logger.info("User logged in via OAuth2 form: %s", user.email)
    return Token(access_token=token)


@router.get("/me", response_model=UserOut)
def read_current_user(current_user: User = Depends(get_current_user)):
    """Return the currently authenticated user's profile."""
    return UserOut(id=current_user.id, email=current_user.email, role_name=current_user.role.name if current_user.role else None)
